import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'hi' | 'mr';

const translations: Record<Language, Record<string, string>> = {
  en: {
    systemTitle: 'DRISHTI',
    systemSubtitle: 'Intelligent Land Record Digitization & Validation System',
    department: 'Department of Land Resources | Ministry of Rural Development',
    govBar: 'GOVERNMENT OF INDIA',
    dashboard: 'Dashboard',
    uploadDocuments: 'Upload Documents',
    batches: 'Batches',
    processingQueue: 'Processing Queue',
    documents: 'Documents',
    verificationQueue: 'Verification Queue',
    myTasks: 'My Tasks',
    districtOverview: 'District Overview',
    teamPerformance: 'Team Performance',
    stateProgress: 'State Progress',
    digitizationAnalytics: 'Digitization Analytics',
    gisMap: 'GIS Cadastral Map',
    auditLogs: 'Audit Logs',
    learningLoop: 'AI Feedback Loop',
    rulesConfig: 'Validation Rules',
    userManagement: 'User Management',
    reports: 'Reports',
    search: 'Global Search',
    teamWorkload: 'Team Workload & SLA',
    nationalOverview: 'National & State Overview',
    allRecords: 'All Verified Records',
    lrmsGateway: 'LRMS / DILRMP Gateway',
    activeScope: 'Active Scope',
    allDistricts: 'All Districts',
    statutoryNoticeTitle: 'Statutory Notice',
    statutoryNotice: 'AI extraction is assistive. Final legal validity resides with authorized revenue officers.',
    status: 'Status',
    confidence: 'AI Confidence',
    quality: 'Quality Score',
    surveyNumber: 'Survey / Gat No.',
    khasraNumber: 'Khasra Number',
    khataNumber: 'Khata Number',
    hissaNumber: 'Hissa Number',
    ownerName: 'Landholder / Owner Name',
    fatherHusbandName: 'Father / Husband Name',
    sharePercentage: 'Share Percentage',
    ownershipClass: 'Ownership Class',
    area: 'Area',
    areaUnit: 'Area Unit',
    village: 'Village',
    tehsil: 'Tehsil / Taluka',
    district: 'District',
    state: 'State',
    actions: 'Actions',
    approve: 'Approve Record',
    reject: 'Reject Record',
    escalate: 'Escalate to Officer',
    saveCorrections: 'Save Corrections',
    rerunValidation: 'Re-run Validation',
    syncToLrms: 'Sync to DILRMP',
    synced: 'Synced',
    reviewRequired: 'Review Required',
    autoAccepted: 'Auto Accepted',
    failed: 'Failed',
    processing: 'Processing',
    uploaded: 'Uploaded',
    approved: 'Approved',
    rejected: 'Rejected',
    escalated: 'Escalated',
    inReview: 'In Review',
    pending: 'Pending',
    switchRole: 'Switch Role',
    activeRole: 'Active Role',
    demoNotice: 'Demonstration System — All actions persisted to active database',
    recordOfRights: 'Record of Rights (7/12 Extract)',
    mutationRegister: 'Mutation Register (Ferfar Nond)',
    saleDeed: 'Sale Deed (Kharidikhata)',
    cadastralMap: 'Cadastral Map Sheet',
    landRegister: 'Land Register (8-A Khata)',
    locationHierarchy: 'Geographical Hierarchy',
    parcelDetails: 'Parcel Geometry & Area',
    ownershipSchedule: 'Ownership & Shares Schedule',
    landClassification: 'Land Classification & Crops (Form 12)',
    mutationRegistration: 'Mutation & Registration Records',
    totalRecords: 'Total Land Records',
    autoAcceptRate: 'Auto-Acceptance Rate',
    avgConfidence: 'Avg AI Confidence',
    quickUpload: 'Upload New Document',
    viewDocument: 'Verify Document',
    backToQueue: 'Back to Queue',
    languageName: 'English',
  },
  hi: {
    systemTitle: 'दृष्टि (DRISHTI)',
    systemSubtitle: 'इंटेलिजेंट भू-अभिलेख डिजिटलीकरण एवं सत्यापन प्रणाली',
    department: 'भूमि संसाधन विभाग | ग्रामीण विकास मंत्रालय, भारत सरकार',
    govBar: 'भारत सरकार | GOVERNMENT OF INDIA',
    dashboard: 'डैशबोर्ड',
    uploadDocuments: 'दस्तावेज़ अपलोड करें',
    batches: 'बैच प्रबंधन',
    processingQueue: 'प्रसंस्करण कतार',
    documents: 'भू-अभिलेख',
    verificationQueue: 'सत्यापन कतार',
    myTasks: 'मेरे कार्य',
    districtOverview: 'जिला अवलोकन',
    teamPerformance: 'सत्यापन दल प्रदर्शन',
    stateProgress: 'राज्य प्रगति',
    digitizationAnalytics: 'डिजिटलीकरण विश्लेषण',
    gisMap: 'जीआईएस भू-नक्शा (GIS)',
    auditLogs: 'ऑडिट लॉग्स',
    learningLoop: 'एआई फीडबैक लूप',
    rulesConfig: 'सत्यापन नियम',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    reports: 'प्रतिवेदन (Reports)',
    search: 'अभिलेख खोजें',
    teamWorkload: 'कार्यभार व SLA',
    nationalOverview: 'राष्ट्रीय एवं राज्य अवलोकन',
    allRecords: 'सभी सत्यापित भू-अभिलेख',
    lrmsGateway: 'DILRMP / LRMS राष्ट्रीय गेटवे',
    activeScope: 'सक्रिय कार्यक्षेत्र',
    allDistricts: 'सभी जिले',
    statutoryNoticeTitle: 'सांविधिक सूचना',
    statutoryNotice: 'एआई द्वारा निष्कर्षित डेटा केवल सहायक है। अंतिम कानूनी वैधता केवल अधिकृत राजस्व अधिकारियों के पास है।',
    status: 'स्थिति',
    confidence: 'सटीकता (Confidence)',
    quality: 'गुणवत्ता सूचकांक',
    surveyNumber: 'भूमापन / सर्वे क्र.',
    khasraNumber: 'खसरा क्रमांक',
    khataNumber: 'खाता क्रमांक',
    hissaNumber: 'हिस्सा क्रमांक',
    ownerName: 'भूस्वामी / खातेदार का नाम',
    fatherHusbandName: 'पिता / पति का नाम',
    sharePercentage: 'अंश प्रतिशत',
    ownershipClass: 'स्वामित्व श्रेणी',
    area: 'क्षेत्रफल',
    areaUnit: 'क्षेत्रफल इकाई',
    village: 'गांव (Village)',
    tehsil: 'तहसील (Tehsil)',
    district: 'जिला (District)',
    state: 'राज्य (State)',
    actions: 'कार्रवाई',
    approve: 'अभिलेख स्वीकृत करें',
    reject: 'अभिलेख अस्वीकृत करें',
    escalate: 'उच्चाधिकारी को भेजें',
    saveCorrections: 'सुधार सहेजें',
    rerunValidation: 'नियम पुनः सत्यापित करें',
    syncToLrms: 'DILRMP के साथ सिंक करें',
    synced: 'सिंक संपन्न',
    reviewRequired: 'सत्यापन आवश्यक',
    autoAccepted: 'स्वतः स्वीकृत',
    failed: 'अयशस्वी',
    processing: 'प्रक्रिया चालू',
    uploaded: 'अपलोड किया गया',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    escalated: 'उच्चाधिकारी को भेजा',
    inReview: 'सत्यापन जारी',
    pending: 'प्रलंबित',
    switchRole: 'भूमिका बदलें',
    activeRole: 'सक्रिय भूमिका',
    demoNotice: 'प्रायोगिक प्रणाली — सभी प्रविष्टियां डेटाबेस में सहेजी जाती हैं',
    recordOfRights: 'अधिकार अभिलेख (7/12 खतौनी)',
    mutationRegister: 'नामांतरण रजिस्टर (दाखिल-खारिज)',
    saleDeed: 'बैनामा / विक्रय विलेख',
    cadastralMap: 'भू-नक्शा / सजरा',
    landRegister: 'खाता रजिस्टर (8-ए)',
    locationHierarchy: 'भौगोलिक पदानुक्रम',
    parcelDetails: 'पार्सल एवं क्षेत्रफल विवरण',
    ownershipSchedule: 'स्वामित्व एवं अंशधारक विवरण',
    landClassification: 'भूमि वर्गीकरण एवं फसल विवरण',
    mutationRegistration: 'दाखिल-खारिज व पंजीयन विवरण',
    totalRecords: 'कुल भू-अभिलेख',
    autoAcceptRate: 'स्वतः स्वीकृति दर',
    avgConfidence: 'औसत सटीकता',
    quickUpload: 'नया दस्तावेज़ अपलोड करें',
    viewDocument: 'दस्तावेज़ जांचें',
    backToQueue: 'कतार में वापस जाएं',
    languageName: 'हिन्दी',
  },
  mr: {
    systemTitle: 'दृष्टी (DRISHTI)',
    systemSubtitle: 'प्रगत भू-अभिलेख संगणकीकरण, बहुभाषिक OCR व पडताळणी प्रणाली',
    department: 'भूमी अभिलेख विभाग | महसूल व वन विभाग, महाराष्ट्र शासन / DoLR',
    govBar: 'भारत सरकार व महाराष्ट्र शासन महसूल विभाग',
    dashboard: 'डॅशबोर्ड',
    uploadDocuments: 'कागदपत्रे अपलोड करा',
    batches: 'बॅच व्यवस्थापन',
    processingQueue: 'प्रक्रिया रांग',
    documents: 'जमीन अभिलेख',
    verificationQueue: 'पडताळणी रांग',
    myTasks: 'माझी प्रलंबित कामे',
    districtOverview: 'जिल्हावार आढावा',
    teamPerformance: 'पडताळणी पथक कामगिरी',
    stateProgress: 'राज्य प्रगती अहवाल',
    digitizationAnalytics: 'डिजिटलायझेशन विश्लेषण',
    gisMap: 'जीआयएस भू-नकाशा (GIS Map)',
    auditLogs: 'ऑडिट लॉग्स व फेरफार इतिहास',
    learningLoop: 'एआय अभिप्राय लूप (Feedback)',
    rulesConfig: 'महसूल पडताळणी नियम',
    userManagement: 'वापरकर्ता व तलाठी व्यवस्थापन',
    reports: 'महसूल अहवाल (Reports)',
    search: 'अभिलेख शोधा (Search)',
    teamWorkload: 'कामाचा ताण व SLA व्यवस्थापन',
    nationalOverview: 'राज्य व राष्ट्रीय विहंगावलोकन',
    allRecords: 'सर्व प्रमाणित भू-अभिलेख',
    lrmsGateway: 'DILRMP / महाभूमी LRMS गेटवे',
    activeScope: 'सक्रिय कार्यक्षेत्र',
    allDistricts: 'सर्व जिल्हे',
    statutoryNoticeTitle: 'वैधानिक सूचना (Statutory Notice)',
    statutoryNotice: 'एआय काढलेली माहिती सहाय्यक आहे. अंतिम कायदेशीर व महसूल वैधता केवळ सक्षम महसूल अधिकाऱ्यांच्या स्वाक्षरीनेच प्राप्त होते.',
    status: 'स्थिती',
    confidence: 'एआय अचूकता',
    quality: 'दस्ताऐवज गुणवत्ता',
    surveyNumber: 'सर्व्हे क्र. / गट क्रमांक',
    khasraNumber: 'खसरा क्रमांक',
    khataNumber: 'खाते क्रमांक (८-अ)',
    hissaNumber: 'हिस्सा क्रमांक',
    ownerName: 'कब्जेदार / खातेदाराचे नाव',
    fatherHusbandName: 'वडील / पतीचे नाव',
    sharePercentage: 'हिस्सा टक्केवारी (%)',
    ownershipClass: 'भोगवटादार वर्ग (वर्ग १/२)',
    area: 'क्षेत्रफळ',
    areaUnit: 'क्षेत्रफळ एकक (हेक्टर/आर/एकर)',
    village: 'गाव (Village)',
    tehsil: 'तालुका (Taluka)',
    district: 'जिल्हा (District)',
    state: 'राज्य (State)',
    actions: 'कृती',
    approve: 'अभिलेख मंजूर करा',
    reject: 'अभिलेख नाकारा',
    escalate: 'तहसीलदार/वरिष्ठांकडे पाठवा',
    saveCorrections: 'बदल जतन करा',
    rerunValidation: 'नियम पुन्हा तपासा',
    syncToLrms: 'DILRMP / महाभूमी सह सिंक करा',
    synced: 'सिंक पूर्ण झाले',
    reviewRequired: 'पडताळणी आवश्यक',
    autoAccepted: 'स्वयंचलित मंजूर',
    failed: 'अयशस्वी',
    processing: 'प्रक्रिया चालू आहे',
    uploaded: 'अपलोड झाले',
    approved: 'मंजूर',
    rejected: 'नाकारले',
    escalated: 'वरिष्ठांकडे वर्ग',
    inReview: 'पडताळणी सुरू',
    pending: 'प्रलंबित',
    switchRole: 'भूमिका बदला',
    activeRole: 'सक्रिय भूमिका',
    demoNotice: 'प्रायोगिक प्रणाली — सर्व नोंदी सक्रिय डेटाबेसमध्ये कायमस्वरूपी सेव्ह केल्या जातात',
    recordOfRights: 'अधिकार अभिलेख (७/१२ उतारा)',
    mutationRegister: 'फेरफार नोंदवही (गाव नमुना ६-ड)',
    saleDeed: 'खरेदीखत / विक्री दस्ताऐवज',
    cadastralMap: 'भू-नकाशा / गाव नकाशा (कॅडस्ट्रल)',
    landRegister: 'खाते नोंदवही (गाव नमुना ८-अ)',
    locationHierarchy: 'स्थान माहिती (गाव, तालुका, जिल्हा रचना)',
    parcelDetails: 'गट क्रमांक व क्षेत्रफळ तपशील',
    ownershipSchedule: 'कब्जेदार व हिस्सेदार तपशील',
    landClassification: 'जमीन वर्ग व पिकांची नोंद (गाव नमुना १२)',
    mutationRegistration: 'फेरफार व दस्त नोंदणी तपशील',
    totalRecords: 'एकूण भू-अभिलेख',
    autoAcceptRate: 'स्वयंचलित मंजुरी प्रमाण',
    avgConfidence: 'सरासरी एआय अचूकता',
    quickUpload: 'नवीन दस्तऐवज जोडा',
    viewDocument: 'अभिलेख पहा व तपासा',
    backToQueue: 'रांगेकडे परत जा',
    languageName: 'मराठी',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('mr'); // Default to Marathi / supported

  const toggleLanguage = () => {
    setLanguage((prev) => {
      if (prev === 'en') return 'mr';
      if (prev === 'mr') return 'hi';
      return 'en';
    });
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
