import {
  User,
  DocumentRecord,
  BatchRecord,
  ExtractedRecord,
  ValidationResult,
  AuditLog,
  FeedbackRecord,
  LrmsSyncRecord,
  ValidationRule,
  NotificationItem,
  GisParcel,
} from '../types.js';
import { DatabaseSchema } from './store.js';
import { generateSeedDocumentsAndRecords } from './seedRecords.js';

export function seedInitialData(): DatabaseSchema {
  const now = new Date().toISOString();

  // 1. Seed 30+ Users
  const users: User[] = [
    // Standard Demo logins
    {
      id: 'usr-op-01',
      name: 'Ramesh Patil',
      email: 'operator@drishti.demo',
      phone: '+91 98230 11201',
      role: 'OPERATOR',
      state: 'Maharashtra',
      district: 'Pune',
      tehsil: 'Haveli',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
      createdAt: '2026-01-10T09:00:00.000Z',
      lastLoginAt: now,
    },
    {
      id: 'usr-ver-01',
      name: 'Sunita Deshmukh',
      email: 'verifier@drishti.demo',
      phone: '+91 98230 11202',
      role: 'VERIFIER',
      state: 'Maharashtra',
      district: 'Pune',
      tehsil: 'Haveli',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
      createdAt: '2026-01-10T09:00:00.000Z',
      lastLoginAt: now,
    },
    {
      id: 'usr-sup-01',
      name: 'Anand Kulkarni (SDM)',
      email: 'supervisor@drishti.demo',
      phone: '+91 98230 11203',
      role: 'SUPERVISOR',
      state: 'Maharashtra',
      district: 'Pune',
      tehsil: 'Haveli',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
      createdAt: '2026-01-05T09:00:00.000Z',
      lastLoginAt: now,
    },
    {
      id: 'usr-off-01',
      name: 'Dr. Meera Iyer (IAS)',
      email: 'official@drishti.demo',
      phone: '+91 98230 11204',
      role: 'OFFICIAL',
      state: 'Maharashtra',
      district: 'All',
      tehsil: 'All',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
      createdAt: '2026-01-01T09:00:00.000Z',
      lastLoginAt: now,
    },
    {
      id: 'usr-adm-01',
      name: 'Rajesh Varma (NIC)',
      email: 'admin@drishti.demo',
      phone: '+91 98230 11205',
      role: 'ADMIN',
      state: 'Central',
      district: 'All',
      tehsil: 'All',
      status: 'ACTIVE',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
      createdAt: '2026-01-01T09:00:00.000Z',
      lastLoginAt: now,
    },
  ];

  // Add 25 more users across Pune, Nashik, Satara, Indore, Lucknow
  const locations = [
    { state: 'Maharashtra', district: 'Pune', tehsil: 'Baramati' },
    { state: 'Maharashtra', district: 'Pune', tehsil: 'Shirur' },
    { state: 'Maharashtra', district: 'Nashik', tehsil: 'Niphad' },
    { state: 'Maharashtra', district: 'Satara', tehsil: 'Karad' },
    { state: 'Madhya Pradesh', district: 'Indore', tehsil: 'Sanwer' },
    { state: 'Uttar Pradesh', district: 'Lucknow', tehsil: 'Bakshi Ka Talab' },
  ];

  const firstNames = ['Amit', 'Pooja', 'Suresh', 'Kavita', 'Manoj', 'Deepa', 'Nitin', 'Pallavi', 'Ganesh', 'Varsha', 'Rahul', 'Snehal', 'Vikram', 'Anjali', 'Sachin', 'Priyanka', 'Chetan', 'Aarti', 'Santosh', 'Neeta', 'Mahesh', 'Shweta', 'Dinesh', 'Komal', 'Pradeep'];
  const lastNames = ['Jadhav', 'Shinde', 'Chavan', 'More', 'Kale', 'Pawar', 'Kadam', 'Bhosale', 'Gaikwad', 'Salunkhe', 'Sawant', 'Mane', 'Thorat', 'Tambe', 'Jagatap'];

  firstNames.forEach((fn, idx) => {
    const ln = lastNames[idx % lastNames.length];
    const loc = locations[idx % locations.length];
    const role: User['role'] = idx % 5 === 0 ? 'SUPERVISOR' : idx % 3 === 0 ? 'OPERATOR' : 'VERIFIER';
    users.push({
      id: `usr-gen-${idx + 10}`,
      name: `${fn} ${ln}`,
      email: `${fn.toLowerCase()}.${ln.toLowerCase()}@drishti.demo`,
      phone: `+91 982${String(10000 + idx).padStart(7, '0')}`,
      role,
      state: loc.state,
      district: loc.district,
      tehsil: loc.tehsil,
      status: 'ACTIVE',
      createdAt: '2026-01-15T10:00:00.000Z',
      lastLoginAt: '2026-09-28T14:20:00.000Z',
    });
  });

  // 2. Validation Rules (15 rules as specified)
  const validationRules: ValidationRule[] = [
    {
      id: 'RULE-01',
      name: 'Mandatory Geographical Hierarchy',
      category: 'MANDATORY',
      field: 'location',
      severity: 'ERROR',
      enabled: true,
      description: 'State, District, Tehsil, and Village fields cannot be empty.',
      updatedAt: now,
    },
    {
      id: 'RULE-02',
      name: 'Survey Number Pattern Check',
      category: 'FORMAT',
      field: 'parcel.surveyNumber',
      severity: 'ERROR',
      enabled: true,
      description: 'Survey number must be digits or standard subdivision (e.g., 142 or 142/2A).',
      updatedAt: now,
    },
    {
      id: 'RULE-03',
      name: 'Khasra / Khata Format',
      category: 'FORMAT',
      field: 'parcel.khasraNumber',
      severity: 'WARNING',
      enabled: true,
      description: 'Khasra and Khata numbers must conform to revenue office numbering standards.',
      updatedAt: now,
    },
    {
      id: 'RULE-04',
      name: 'Positive Plot Area Sanity',
      category: 'SANITY',
      field: 'parcel.plotArea',
      severity: 'ERROR',
      enabled: true,
      description: 'Plot area value must be strictly greater than 0.',
      updatedAt: now,
    },
    {
      id: 'RULE-05',
      name: 'Standard Unit Verification',
      category: 'FORMAT',
      field: 'parcel.areaUnit',
      severity: 'WARNING',
      enabled: true,
      description: 'Unit must be one of: Acre, Hectare, Bigha, Guntha, Sq Ft, Sq M.',
      updatedAt: now,
    },
    {
      id: 'RULE-06',
      name: 'Area Normalization Match',
      category: 'SANITY',
      field: 'parcel.normalizedAreaAcres',
      severity: 'WARNING',
      enabled: true,
      description: 'Normalized area in Acres must match calculation within 1% threshold.',
      updatedAt: now,
    },
    {
      id: 'RULE-07',
      name: 'Owner Share Range Check',
      category: 'LOGICAL',
      field: 'ownership.sharePercentage',
      severity: 'ERROR',
      enabled: true,
      description: 'Individual owner share must be between 0.1% and 100%.',
      updatedAt: now,
    },
    {
      id: 'RULE-08',
      name: 'Total Ownership Shares Equal 100%',
      category: 'LOGICAL',
      field: 'ownership.totalSharePercentage',
      severity: 'ERROR',
      enabled: true,
      description: 'Sum of all co-owner shares in a joint parcel must equal exactly 100% (±0.1% tolerance).',
      updatedAt: now,
    },
    {
      id: 'RULE-09',
      name: 'Mutation Date Rationality',
      category: 'LOGICAL',
      field: 'mutation.mutationDate',
      severity: 'ERROR',
      enabled: true,
      description: 'Mutation transaction date cannot be in the future.',
      updatedAt: now,
    },
    {
      id: 'RULE-10',
      name: 'Registration Date Rationality',
      category: 'LOGICAL',
      field: 'registration.registrationDate',
      severity: 'ERROR',
      enabled: true,
      description: 'Sub-registrar registration date cannot be in the future.',
      updatedAt: now,
    },
    {
      id: 'RULE-11',
      name: 'LGD Code Hierarchy Cross-Check',
      category: 'HIERARCHY',
      field: 'location.lgdCodes',
      severity: 'WARNING',
      enabled: true,
      description: 'Local Government Directory codes must map to genuine census/revenue records.',
      updatedAt: now,
    },
    {
      id: 'RULE-12',
      name: 'Duplicate Document Hash Check',
      category: 'DUPLICATE',
      field: 'document.fileHash',
      severity: 'ERROR',
      enabled: true,
      description: 'Detects exact SHA-256 binary duplicate uploads in the system repository.',
      updatedAt: now,
    },
    {
      id: 'RULE-13',
      name: 'Fuzzy Land Record Match',
      category: 'DUPLICATE',
      field: 'parcel.fuzzyMatch',
      severity: 'WARNING',
      enabled: true,
      description: 'Flags overlapping records having identical Village + Survey No + Owner + Area.',
      updatedAt: now,
    },
    {
      id: 'RULE-14',
      name: 'Document Quality Threshold',
      category: 'SANITY',
      field: 'document.qualityScore',
      severity: 'WARNING',
      enabled: true,
      description: 'Quality score must be at least 60/100, otherwise flagged for quality review.',
      updatedAt: now,
    },
    {
      id: 'RULE-15',
      name: 'Maharashtra 7/12 Land Classification Rule',
      category: 'MANDATORY',
      field: 'land.landClassification',
      severity: 'WARNING',
      enabled: true,
      stateScope: 'Maharashtra',
      description: 'Must specify Jirayat (dryland) or Bagayat (irrigated) with water source.',
      updatedAt: now,
    },
  ];

  // 3. Batches
  const batches: BatchRecord[] = [
    {
      id: 'BATCH-2026-001',
      batchNumber: 'MH-PUN-HAV-202609-01',
      name: 'Wagholi Village 7/12 RoR Digitization Drive',
      state: 'Maharashtra',
      district: 'Pune',
      tehsil: 'Haveli',
      village: 'Wagholi',
      documentCount: 24,
      processedCount: 24,
      approvedCount: 18,
      reviewCount: 5,
      failedCount: 1,
      status: 'PARTIALLY_COMPLETED',
      createdBy: 'usr-op-01',
      createdByName: 'Ramesh Patil',
      createdAt: '2026-09-20T10:00:00.000Z',
      updatedAt: now,
    },
    {
      id: 'BATCH-2026-002',
      batchNumber: 'MH-PUN-HAV-202609-02',
      name: 'Koregaon Bhima Mutation Register Legacy Records',
      state: 'Maharashtra',
      district: 'Pune',
      tehsil: 'Haveli',
      village: 'Koregaon Bhima',
      documentCount: 30,
      processedCount: 30,
      approvedCount: 26,
      reviewCount: 4,
      failedCount: 0,
      status: 'COMPLETED',
      createdBy: 'usr-op-01',
      createdByName: 'Ramesh Patil',
      createdAt: '2026-09-22T11:30:00.000Z',
      updatedAt: now,
    },
    {
      id: 'BATCH-2026-003',
      batchNumber: 'MH-SAT-KAR-202609-03',
      name: 'Shindewadi Parcel Cadastral Records & Sale Deeds',
      state: 'Maharashtra',
      district: 'Satara',
      tehsil: 'Karad',
      village: 'Shindewadi',
      documentCount: 28,
      processedCount: 28,
      approvedCount: 22,
      reviewCount: 6,
      failedCount: 0,
      status: 'PROCESSING',
      createdBy: 'usr-gen-10',
      createdByName: 'Amit Jadhav',
      createdAt: '2026-09-25T08:15:00.000Z',
      updatedAt: now,
    },
    {
      id: 'BATCH-2026-004',
      batchNumber: 'UP-LKO-BKT-202609-04',
      name: 'Bakshi Ka Talab Khasra-Khatauni Digitization',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      tehsil: 'Bakshi Ka Talab',
      village: 'Rampur',
      documentCount: 25,
      processedCount: 25,
      approvedCount: 20,
      reviewCount: 4,
      failedCount: 1,
      status: 'PARTIALLY_COMPLETED',
      createdBy: 'usr-gen-15',
      createdByName: 'Manoj Pawar',
      createdAt: '2026-09-26T14:00:00.000Z',
      updatedAt: now,
    },
  ];

  const recs = generateSeedDocumentsAndRecords();

  return {
    users,
    validationRules,
    batches,
    documents: recs.documents,
    extractedRecords: recs.extractedRecords,
    validationResults: recs.validationResults,
    auditLogs: recs.auditLogs,
    feedbackRecords: recs.feedbackRecords,
    lrmsSyncRecords: recs.lrmsSyncRecords,
    notifications: recs.notifications,
    gisParcels: recs.gisParcels,
  };
}
